# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      echo "Using Environment variables"
    env: 
      MYSQL_SERVER_NAME: $(mysql_name)
      MYSQL_SERVER_FULL_NAME: $(server_full_name)
      MYSQL_SERVER_ADMIN_LOGIN_NAME: $(admin_name)
      MYSQL_SERVER_ADMIN_PASSWORD: $(admin_pass)
      MYSQL_DATABASE_NAME: $(database)
      DOLLAR: \$
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false



